/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as EventsSlugImport } from './routes/events/$slug'
import { Route as CalendarDateImport } from './routes/calendar/$date'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EventsSlugRoute = EventsSlugImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRoute,
} as any)

const CalendarDateRoute = CalendarDateImport.update({
  id: '/calendar/$date',
  path: '/calendar/$date',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/calendar/$date': {
      id: '/calendar/$date'
      path: '/calendar/$date'
      fullPath: '/calendar/$date'
      preLoaderRoute: typeof CalendarDateImport
      parentRoute: typeof rootRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar/$date': typeof CalendarDateRoute
  '/events/$slug': typeof EventsSlugRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar/$date': typeof CalendarDateRoute
  '/events/$slug': typeof EventsSlugRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/calendar/$date': typeof CalendarDateRoute
  '/events/$slug': typeof EventsSlugRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar/$date' | '/events/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar/$date' | '/events/$slug'
  id: '__root__' | '/' | '/calendar/$date' | '/events/$slug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarDateRoute: typeof CalendarDateRoute
  EventsSlugRoute: typeof EventsSlugRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarDateRoute: CalendarDateRoute,
  EventsSlugRoute: EventsSlugRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/calendar/$date",
        "/events/$slug"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/calendar/$date": {
      "filePath": "calendar/$date.tsx"
    },
    "/events/$slug": {
      "filePath": "events/$slug.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
