/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as SearchImport } from './routes/search'
import { Route as IndexImport } from './routes/index'
import { Route as EventsSlugImport } from './routes/events/$slug'
import { Route as CalendarDateImport } from './routes/calendar/$date'
import { Route as CalendarYearMonthImport } from './routes/calendar/$year/$month'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const SearchRoute = SearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EventsSlugRoute = EventsSlugImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRoute,
} as any)

const CalendarDateRoute = CalendarDateImport.update({
  id: '/calendar/$date',
  path: '/calendar/$date',
  getParentRoute: () => rootRoute,
} as any)

const CalendarYearMonthRoute = CalendarYearMonthImport.update({
  id: '/calendar/$year/$month',
  path: '/calendar/$year/$month',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/calendar/$date': {
      id: '/calendar/$date'
      path: '/calendar/$date'
      fullPath: '/calendar/$date'
      preLoaderRoute: typeof CalendarDateImport
      parentRoute: typeof rootRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugImport
      parentRoute: typeof rootRoute
    }
    '/calendar/$year/$month': {
      id: '/calendar/$year/$month'
      path: '/calendar/$year/$month'
      fullPath: '/calendar/$year/$month'
      preLoaderRoute: typeof CalendarYearMonthImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/calendar/$date': typeof CalendarDateRoute
  '/events/$slug': typeof EventsSlugRoute
  '/calendar/$year/$month': typeof CalendarYearMonthRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/calendar/$date': typeof CalendarDateRoute
  '/events/$slug': typeof EventsSlugRoute
  '/calendar/$year/$month': typeof CalendarYearMonthRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/calendar/$date': typeof CalendarDateRoute
  '/events/$slug': typeof EventsSlugRoute
  '/calendar/$year/$month': typeof CalendarYearMonthRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/search'
    | '/calendar/$date'
    | '/events/$slug'
    | '/calendar/$year/$month'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/search'
    | '/calendar/$date'
    | '/events/$slug'
    | '/calendar/$year/$month'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/search'
    | '/calendar/$date'
    | '/events/$slug'
    | '/calendar/$year/$month'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SearchRoute: typeof SearchRoute
  CalendarDateRoute: typeof CalendarDateRoute
  EventsSlugRoute: typeof EventsSlugRoute
  CalendarYearMonthRoute: typeof CalendarYearMonthRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SearchRoute: SearchRoute,
  CalendarDateRoute: CalendarDateRoute,
  EventsSlugRoute: EventsSlugRoute,
  CalendarYearMonthRoute: CalendarYearMonthRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/search",
        "/calendar/$date",
        "/events/$slug",
        "/calendar/$year/$month"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/calendar/$date": {
      "filePath": "calendar/$date.tsx"
    },
    "/events/$slug": {
      "filePath": "events/$slug.tsx"
    },
    "/calendar/$year/$month": {
      "filePath": "calendar/$year/$month.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
